### ISSUE TITLE
Typographical Vertical Rhythm

### ISSUE THREAD

**Issue by AlexEJerome** [bitcamp/old-2015-site#26]
Fix Typographical Vertical Rhythm. Yuck.

![eh](http://s3.amazonaws.com/awesome_screenshot/7085252?AWSAccessKeyId=0R7FMW7AXRVCYMAPTPR2&Expires=1421616249&Signature=WQ9l8b%2BTHiyAtCZk9gaktNWN1Z0%3D)

**Comment by AntCas** [comment]
Your link is broken, but you are very right.

**Comment by AntCas** [comment]
Should be better now.
