### ISSUE TITLE
Fix title in moble.

### ISSUE THREAD

**Issue by AlexEJerome** [bitcamp/old-2015-site#27]
![meh](http://s3.amazonaws.com/awesome_screenshot/7085252?AWSAccessKeyId=0R7FMW7AXRVCYMAPTPR2&Expires=1421616249&Signature=WQ9l8b%2BTHiyAtCZk9gaktNWN1Z0%3D)

**Comment by AntCas** [comment]
Your link is broken but I fixed the title going off screen.
