### ISSUE TITLE
Social Link Images

### ISSUE THREAD

**Issue by AntCas** [bitcamp/old-2015-site#28]
Images are not up to date with current design. Remind Jeff to upload.

**Comment by AlexEJerome** [comment]
@AntCas Export PNG's from AI file on Google Drive.

**Comment by AntCas** [comment]
@AlexEJerome Jeff already said he's on it, but I will if need be. It's a bit of a hassle for me bc I have to restart my computer. (I use Ubuntu, dual boot Windows where Illustrator lives)

**Comment by AlexEJerome** [comment]
you're too fancy ;)
Ubuntu is some hardcore stuff and sounds good.
