### ISSUE TITLE
You're Off The Grid!

### ISSUE THREAD

**Issue by AlexEJerome** [bitcamp/old-2015-site#29]
Not to be nitpicky, but you need to make sure you're using a percentage-based grid. Not doing so makes the content feel "awkward" and off balance relative to the other content. Look at the mockup png (if the AI is too hard to access) at the sponsor section and match the 12 col grid up to the content. I know it's not easy, but it's worth it.

**Comment by AntCas** [comment]
grid applied wherever appropriate
